sudo: required
services: docker
language: minimal
branches:
  only:
  - master
script:
  - DOCKER_CONTENT_TRUST=1 docker build --pull -t "bsycorp/debian-build-tools:1.0.$TRAVIS_BUILD_NUMBER" -t "bsycorp/debian-build-tools:latest" .
  - docker login -u $DOCKERUSER -p $DOCKERPASS
  - docker push bsycorp/debian-build-tools